services:
  - type: web
    name: site-m2d
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: CSRF_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: site-m2d-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: site-m2d-db
    databaseName: site_m2d
    user: site_m2d_user
    plan: free 