"""Migração inicial limpa

Revision ID: 3c20ab6c56e1
Revises: 
Create Date: 2025-06-07 19:05:59.888714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c20ab6c56e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('condominio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('numero_apartamentos', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('sindico_id', sa.Integer(), nullable=True),
    sa.Column('administrador', sa.String(length=100), nullable=True),
    sa.Column('contato', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sindico_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=False),
    sa.Column('usuario_remetente_id', sa.Integer(), nullable=True),
    sa.Column('assunto', sa.String(length=120), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['usuario_remetente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_lancamento', sa.DateTime(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('resolvida', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('motivo_desistencia', sa.Text(), nullable=True),
    sa.Column('atividade', sa.String(length=70), nullable=False),
    sa.Column('aprovado_por_id', sa.Integer(), nullable=True),
    sa.Column('motivo_correcao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividade')
    op.drop_table('mensagem')
    op.drop_table('condominio')
    op.drop_table('user')
    # ### end Alembic commands ###
