"""renomear_sindico_id_para_supervisor_id

Revision ID: 5fd84338b5e4
Revises: 3c20ab6c56e1
Create Date: 2025-06-09 23:33:58.205141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd84338b5e4'
down_revision = '3c20ab6c56e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividade')
    op.drop_table('condominio')
    op.drop_table('user')
    op.drop_table('mensagem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_destino_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_remetente_id', sa.INTEGER(), nullable=True),
    sa.Column('assunto', sa.VARCHAR(length=120), nullable=False),
    sa.Column('corpo', sa.TEXT(), nullable=False),
    sa.Column('lida', sa.BOOLEAN(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['usuario_remetente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=60), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('condominio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=False),
    sa.Column('numero_apartamentos', sa.INTEGER(), nullable=False),
    sa.Column('data_entrada', sa.DATE(), nullable=True),
    sa.Column('sindico_id', sa.INTEGER(), nullable=True),
    sa.Column('administrador', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contato', sa.VARCHAR(length=30), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['sindico_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_lancamento', sa.DATETIME(), nullable=False),
    sa.Column('condominio_id', sa.INTEGER(), nullable=False),
    sa.Column('responsavel_id', sa.INTEGER(), nullable=False),
    sa.Column('criado_por_id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('data_entrega', sa.DATE(), nullable=False),
    sa.Column('resolvida', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('motivo_desistencia', sa.TEXT(), nullable=True),
    sa.Column('atividade', sa.VARCHAR(length=70), nullable=False),
    sa.Column('aprovado_por_id', sa.INTEGER(), nullable=True),
    sa.Column('motivo_correcao', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
