"""add campos crm e data_entrada ao condominio

Revision ID: 876baee42475
Revises: addrole001
Create Date: 2025-06-14 16:43:39.992884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876baee42475'
down_revision = 'addrole001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_entrada', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('administrador_nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('administrador_telefone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('administrador_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.drop_column('administrador_email')
        batch_op.drop_column('administrador_telefone')
        batch_op.drop_column('administrador_nome')
        batch_op.drop_column('data_entrada')

    # ### end Alembic commands ###
