"""Altera logo_filename para logo_url em Property

Revision ID: 9a973462045d
Revises: ce2a8dd9507a
Create Date: 2025-07-29 21:28:19.597721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a973462045d'
down_revision = 'ce2a8dd9507a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
